spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/apidb
    username: apidbuser
    password: apidbuser
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: info

