spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/apidb
    username: apidbuser
    password: apidbuser
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    sql: info

org:
  zerock:
    upload:
      path: upload
